[project]
name = "fly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anders Bogsnes", email = "andersbognes@gmail.com" }
]
requires-python = ">=3.11,<3.14"
dependencies = [
    "cyclopts>=4.22.3",
    "httpx2>=2.9.1",
    "jupyterlab>=4.6.2",
    "pyarrow>=25.0.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyiceberg>=0.11.1",
    "python-on-whales>=0.81.0",
    "rich>=14.3.4",
    "sqlalchemy>=2.0.51",
    "uvicorn>=0.52.0",
    "rest",
    "flight_server",
    "duckdb>=1.5.5",
    "connectorx>=0.4.5",
    "adbc-driver-postgresql>=1.12.0",
]

[project.scripts]
fly = "fly.cli:app.meta"

[tool.uv.sources]
flight_server = { workspace = true }
rest = { workspace = true }

[tool.uv.workspace]
members = [
    "flight_server",
    "rest",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyrefly>=1.2.0",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]

