import datetime as dt
import json
from collections.abc import Iterator
from typing import cast

import polars as pl
import pyarrow as pa
import structlog
from pyarrow import flight
from pyiceberg.catalog.rest import RestCatalog
from pyiceberg.exceptions import BadRequestError, NoSuchTableError, RESTError
from pyiceberg.expressions import AlwaysTrue, GreaterThanOrEqual, LessThanOrEqual

from flight_server import metrics
from flight_server.exceptions import IcebergCatalogueException
from flight_server.models import (
    CreateNamespaceRequest,
    DeleteDatasetRequest,
    DoPutResponse,
    GetDatasetRequest,
    UpdateDatasetRequest,
)
from flight_server.settings import Settings

logger: structlog.typing.FilteringBoundLogger = structlog.get_logger(__name__)


class Server(flight.FlightServerBase):
    """
    Arrow Flight is GRPC-based, so the Flight Server is defined by a Protobuf Service RPC.
    The actual Protobufs are defined here:
    https://arrow.apache.org/docs/format/Flight.html#protocol-buffer-definitions.
    The server stub is then autogenerated from the Protobufs.
    """

    def __init__(
        self,
        settings: Settings,
        location: str = "grpc://localhost:7000",
        workers: list[str] | None = None,
        auth_handler: flight.ServerAuthHandler | None = None,
    ):
        super().__init__(location=location, auth_handler=auth_handler)
        self._location = location
        self._workers = [] if workers is None else workers
        self._namespace = settings.namespace
        self._rest_catalog = None
        self._catalog_config = {
            "uri": settings.catalog_url,
            "warehouse": settings.warehouse,
        }

        if settings.mode == "aws":
            aws_opts = {
                "rest.sigv4-enabled": "true",
                "rest.signing-name": "s3tables",
                "rest.signing-region": "eu-north-1",
            }
            self._catalog_config |= aws_opts

    @property
    def _catalog(self) -> RestCatalog:
        if self._rest_catalog is None:
            try:
                catalog = RestCatalog("default", **self._catalog_config)
            except RESTError as e:
                raise IcebergCatalogueException(
                    "unable to connect to Iceberg Catalog"
                ) from e
            return catalog
        return self._rest_catalog

    def _make_flight_info(self, identifier: str) -> flight.FlightInfo:
        """
        FlightInfo is the metadata for a dataset. We make it from the Iceberg table metadata
        """
        log = logger.bind(identifier=identifier, method="_make_flight_info")
        try:
            table = self._catalog.load_table(identifier)
        except NoSuchTableError:
            log.error("No such table")
            raise flight.FlightServerError(f"{identifier} not found")
        request = GetDatasetRequest(identifier=identifier)
        ticket = flight.Ticket(request.model_dump_json().encode("utf-8"))
        log.debug("ticket encoded", request=request)

        endpoints = [
            flight.FlightEndpoint(
                ticket=ticket,
                locations=[self._location, *self._workers],
            )
        ]

        snapshot = table.current_snapshot()
        num_rows = -1
        total_bytes = -1

        if snapshot is not None and snapshot.summary is not None:
            num_rows = int(snapshot.summary.get("total-records", -1))
            total_bytes = int(snapshot.summary.get("total-files-size", -1))
            log = log.bind(num_rows=num_rows, total_bytes=total_bytes)
        else:
            log.info("no snapshot found")
        log.debug("building flightinfo")

        return flight.FlightInfo(
            schema=table.schema().as_arrow(),
            descriptor=flight.FlightDescriptor.for_path(identifier),
            endpoints=endpoints,
            total_records=num_rows,
            total_bytes=total_bytes,
            app_metadata=json.dumps(
                {"description": table.properties.get("description", "")}
            ),
        )

    def do_get(
        self, _: flight.ServerCallContext, ticket: flight.Ticket
    ) -> flight.FlightDataStream:
        """
        When a client calls get_flight_info, it will get a Ticket which we defined.
        The Ticket describes to the server how to get the data and contains an arbitrary payload
        only meant for the server to understand.
        """
        # We decided on JSON for the ticket payload, so we decode it here.
        request = GetDatasetRequest.model_validate_json(ticket.ticket.decode("utf-8"))
        log = logger.bind(request=request, method="do_get")
        table = self._catalog.load_table(request.identifier)

        filters = AlwaysTrue() if request.filters is None else request.filters

        reader = table.scan(
            selected_fields=request.columns,
            row_filter=filters,
        ).to_arrow_batch_reader()

        def gen():
            try:
                yield from reader
            finally:
                # Always close the dataset when we're done.'
                reader.close()

        log.info("starting stream")
        # Because Flight is GRPC-based, it supports streaming the data by default.
        return flight.GeneratorStream(
            schema=table.schema().as_arrow(),
            generator=gen(),
        )

    def get_schema(
        self, _: flight.ServerCallContext, descriptor: flight.FlightDescriptor
    ) -> flight.SchemaResult:
        """Get the schema of the dataset."""
        table_name = descriptor.path[0].decode("utf-8")
        log = logger.bind(table_name=table_name, method="get_schema")
        try:
            table = self._catalog.load_table(table_name)
        except NoSuchTableError:
            log.error("no such table")
            raise flight.FlightServerError(f"{table_name} not found")

        schema = table.schema().as_arrow()
        return flight.SchemaResult(schema)

    def get_flight_info(
        self, _: flight.ServerCallContext, descriptor: flight.FlightDescriptor
    ) -> flight.FlightInfo:
        """The client can ask for the metadata for a dataset by calling get_flight_info.
        They will use a human-readable FlightDescriptor to describe the dataset they want.
        The FlightDescriptor can either be a path, or a command, but the definition is up to the
        implementer.

        The job of the FlightInfo is to return to the client where the data can be fetched
        from, build a Ticket for the Client to use to ask for the actual data, and provide
        some metadata such as the schema, number of rows, and size.
        """
        identifier = f"{self._namespace}.{descriptor.path[0].decode('utf-8')}"
        log = logger.bind(method="get_flight_info", identifier=identifier)
        log.info("getting flight info")
        return self._make_flight_info(identifier)

    def list_flights(
        self, _: flight.ServerCallContext, criteria: bytes
    ) -> Iterator[flight.FlightInfo]:
        """Flight has native support for data discovery. The client can ask for all available
         flights and can send criteria to filter, where the criteria implementation is up to
        the implementer.
        """
        filter_match = criteria.decode("utf-8")
        log = logger.bind(filter_match=filter_match, method="list_flights")
        # catalog.list_tables returns a tuple of (namespace, table_name)
        table_identifiers = [
            ".".join(t)
            for t in self._catalog.list_tables(self._namespace)
            if filter_match.lower() in t[1].lower()
        ]
        log.info("listing flights")
        for identifier in table_identifiers:
            yield self._make_flight_info(identifier)

    def do_put(
        self,
        _: flight.ServerCallContext,
        descriptor: flight.FlightDescriptor,
        reader: flight.FlightStreamReader,
        writer: flight.FlightMetadataWriter,
    ):
        """Do_put is responsible for writing the data to storage. The client will send an
        Arrow Table, and the server will write it to storage. It can also send metadata back
        to the client, such as the number of rows written.
        """
        table_name = f"{self._namespace}.{descriptor.path[0].decode('utf-8')}"
        log = logger.bind(table_name=table_name, method="do_put")
        if not self._catalog.table_exists(table_name):
            log.info("creating table")
            try:
                table = self._catalog.create_table(table_name, reader.schema)
            except BadRequestError:
                log.error("unable to create table")
                raise flight.FlightServerError("unable to create table")

        else:
            log.info("loading table")
            table = self._catalog.load_table(table_name)

        with table.transaction() as tx:
            total_rows = 0
            batches = []
            row_count = 0
            for chunk in reader:
                batches.append(chunk.data)
                row_count += chunk.data.num_rows
                total_rows += chunk.data.num_rows
                if row_count >= 1_000_000:
                    pa_table = pa.Table.from_batches(batches, reader.schema)
                    tx.append(pa_table)
                    batches = []
                    row_count = 0

            if batches:
                pa_table = pa.Table.from_batches(batches, reader.schema)
                tx.append(pa_table)

        response = DoPutResponse(
            total_rows=total_rows,
        )
        writer.write(response.model_dump_json(exclude_unset=True).encode())

    def list_actions(self, _: flight.ServerCallContext) -> Iterator[flight.ActionType]:
        """Flight has native support for actions.
        Actions are a way to perform arbitrary operations, and list_actions is a discovery
        mechanism for the client to find out what actions are available.
        """
        actions = [
            (
                "create_namespace",
                json.dumps(
                    {
                        "description": "Create a new namespace",
                        "schema": CreateNamespaceRequest.model_json_schema(),
                    }
                ),
            ),
            (
                "update_description",
                json.dumps(
                    {
                        "description": "Update a dataset description",
                        "schema": UpdateDatasetRequest.model_json_schema(),
                    }
                ),
            ),
            (
                "delete_dataset",
                json.dumps(
                    {
                        "description": "Delete a dataset",
                        "schema": DeleteDatasetRequest.model_json_schema(),
                    }
                ),
            ),
            (
                "get_active_user",
                json.dumps(
                    {
                        "description": "Get the active user",
                        "schema": None,
                    }
                ),
            ),
        ]

        for action in actions:
            yield flight.ActionType(action[0], action[1])

    def do_action(
        self, context: flight.ServerCallContext, action: flight.Action
    ) -> Iterator[bytes]:
        """When the client wants to perform an action, it will send an Action via do_action.
        What that action does is completely up to the implementation.
        """
        match action.type:
            case "create_namespace":
                request = CreateNamespaceRequest.model_validate_json(
                    action.body.to_pybytes().decode("utf-8")
                )
                self._catalog.create_namespace(request.name)
            case "update_description":
                request = UpdateDatasetRequest.model_validate_json(
                    action.body.to_pybytes().decode("utf-8")
                )
                try:
                    table = self._catalog.load_table(request.name)
                except NoSuchTableError:
                    raise flight.FlightServerError(
                        f"Table {request.name} does not exist"
                    )
                with table.transaction() as tx:
                    tx.set_properties({"description": request.description})

                yield f"Updated dataset {request.name} description".encode()
            case "delete_dataset":
                request = DeleteDatasetRequest.model_validate_json(
                    action.body.to_pybytes().decode("utf-8")
                )
                try:
                    self._catalog.drop_table(request.name)
                except NoSuchTableError:
                    raise flight.FlightServerError(
                        f"Table {request.name} does not exist"
                    )

                yield f"Deleted dataset {request.name}".encode()
            case "get_active_user":
                user = context.peer_identity()
                yield user
            case _:
                raise flight.FlightServerError(f"Unknown action: {action.type}")

    def do_exchange(
        self,
        _: flight.ServerCallContext,
        descriptor: flight.FlightDescriptor,
        reader: flight.FlightStreamReader,
        writer: flight.FlightStreamWriter,
    ):
        """Flight can receive and send data within the same call using do_exchange.
        This is commonly used for enriching data, such as calling an ML model to enrich the data,
        or calculate some metric on the data.
        """
        cmd: str = json.loads(descriptor.command.decode("utf-8"))["metric"]
        match cmd:
            case "ctr":
                sample_ctr_data: pa.Table = reader.read_all()
                df = pl.DataFrame(sample_ctr_data)
                min_date = cast(dt.date, df["date"].min())
                max_date = cast(dt.date, df["date"].max())

                sample_ctr = metrics.calculate_ctr(sample_ctr_data)

                table = self._catalog.load_table(f"{self.namespace}.metrics")

                total_data = table.scan(
                    row_filter=GreaterThanOrEqual(term="date", value=min_date)
                    & LessThanOrEqual(term="date", value=max_date),
                    selected_fields=("date", "is_clicked"),
                ).to_arrow()

                total_ctr = metrics.calculate_ctr(total_data)
                result = total_ctr.append_column("sample_ctr", sample_ctr["click_rate"])
                writer.begin(result.schema)
                writer.write_table(result)
            case _:
                raise flight.FlightServerError(f"Unknown command: {cmd}")
