import datetime as dt
import json
from typing import Iterator, cast

import polars as pl
import pyarrow as pa
from pyarrow import flight
from pyarrow.fs import FileSystem
from pyiceberg.catalog.rest import RestCatalog
from pyiceberg.exceptions import NoSuchTableError
from pyiceberg.expressions import GreaterThanOrEqual, LessThanOrEqual

from taking_flight.flight_server import metrics
from taking_flight.flight_server.models import (
    Dataset,
    DeleteDatasetRequest,
    UpdateDatasetRequest,
)
from taking_flight.flight_server.repo import DatasetRepo


class Server(flight.FlightServerBase):
    """
    Arrow Flight is GRPC-based, so the Flight Server is defined by a Protobuf Service RPC.
    The actual Protobufs are defined here:
    https://arrow.apache.org/docs/format/Flight.html#protocol-buffer-definitions.
    The server stub is then autogenerated from the Protobufs.
    """

    def __init__(
            self,
            fs: FileSystem,
            dataset_repo: DatasetRepo,
            catalog: RestCatalog,
            bucket_name: str = "events",
            location: str = "grpc://localhost:3000",
            workers: list[str] | None = None,
            auth_handler: flight.ServerAuthHandler | None = None,
            namespace: str = "default",
    ):
        super().__init__(location=location, auth_handler=auth_handler)
        self._bucket_name = bucket_name
        self._location = location
        self._fs = fs
        self._dataset_repo = dataset_repo
        self._workers = [] if workers is None else workers
        self._catalog = catalog
        self._namespace = namespace

    def _make_flight_info(self, identifier: str) -> flight.FlightInfo:
        """
        FlightInfo is the metadata for a dataset. We make it from the Iceberg table metadata
        """
        try:
            table = self._catalog.load_table(identifier)
        except NoSuchTableError:
            raise flight.FlightServerError(f"{identifier} not found")


        ticket = flight.Ticket(identifier)

        endpoints = [
            flight.FlightEndpoint(
                ticket=ticket,
                locations=[self._location, *self._workers],
            )
        ]

        snapshot = table.current_snapshot()
        num_rows = -1
        total_bytes = -1

        if snapshot is not None and snapshot.summary is not None:
            num_rows = snapshot.summary.get("total-records", -1)
            total_bytes = snapshot.summary.get("total-files-size", -1)

        return flight.FlightInfo(
            schema=table.schema().as_arrow(),
            descriptor=flight.FlightDescriptor.for_path(identifier),
            endpoints=endpoints,
            total_records=num_rows,
            total_bytes=total_bytes,
            app_metadata=json.dumps({"description": table.properties.get("description", "")}),
        )

    def do_get(
            self, _: flight.ServerCallContext, ticket: flight.Ticket
    ) -> flight.FlightDataStream:
        """
        When a client calls get_flight_info, it will get a Ticket which we defined.
        The Ticket describes to the server how to get the data and contains an arbitrary payload
        only meant for the server to understand.
        """
        # We decided on JSON for the ticket payload, so we decode it here.
        dataset = Dataset.model_validate_json(ticket.ticket.decode("utf-8"))

        table = self._catalog.load_table(dataset.identifier)

        reader = table.scan().to_arrow_batch_reader()

        def gen():
            try:
                for batch in reader:
                    yield batch
            finally:
                # Always close the dataset when we're done.'
                reader.close()

        # Because Flight is GRPC-based, it supports streaming the data by default.
        return flight.GeneratorStream(
            schema=table.schema().as_arrow(),
            generator=gen(),
        )

    def get_schema(
            self, _: flight.ServerCallContext, descriptor: flight.FlightDescriptor
    ) -> flight.SchemaResult:
        """Get the schema of the dataset."""
        table_name = descriptor.path[0].decode("utf-8")

        try:
            table = self._catalog.load_table(table_name)
        except NoSuchTableError:
            raise flight.FlightServerError(f"{table_name} not found")

        schema = table.schema().as_arrow()
        return flight.SchemaResult(schema)

    def get_flight_info(
            self, _: flight.ServerCallContext, descriptor: flight.FlightDescriptor
    ) -> flight.FlightInfo:
        """The client can ask for the metadata for a dataset by calling get_flight_info.
        They will use a human-readable FlightDescriptor to describe the dataset they want.
        The FlightDescriptor can either be a path, or a command, but the definition is up to the
        implementer.

        The job of the FlightInfo is to return to the client where the data can be fetched
        from, build a Ticket for the Client to use to ask for the actual data, and provide
        some metadata such as the schema, number of rows, and size.
        """
        identifier = descriptor.path[0].decode("utf-8")
        return self._make_flight_info(identifier)

    def list_flights(
            self, context: flight.ServerCallContext, criteria: bytes
    ) -> Iterator[flight.FlightInfo]:
        """Flight has native support for data discovery. The client can ask for all available
         flights and can send criteria to filter, where the criteria implementation is up to
        the implementer.
        """
        filter_match = criteria.decode("utf-8")
        # catalog.list_tables returns a tuple of (namespace, table_name)
        table_identifiers = [".".join(t)
                             for t in self._catalog.list_tables(self._namespace)
                             if filter_match.lower() in t[1].lower()]

        for identifier in table_identifiers:
            yield self._make_flight_info(identifier)

    def do_put(
            self,
            _: flight.ServerCallContext,
            descriptor: flight.FlightDescriptor,
            reader: flight.FlightStreamReader,
            writer: flight.FlightMetadataWriter,
    ):
        """Do_put is responsible for writing the data to storage. The client will send an
        Arrow Table, and the server will write it to storage. It can also send metadata back
        to the client, such as the number of rows written.
        """
        table_name = f"{self._namespace}.{descriptor.path[0].decode("utf-8")}"

        if not self._catalog.table_exists(table_name):
            table = self._catalog.create_table(table_name, reader.schema)
        else:
            table = self._catalog.load_table(table_name)

        with table.transaction() as tx:
            for chunk in reader:
                pa_table = pa.Table.from_batches([chunk.data], table.schema().as_arrow())
                tx.append(pa_table)

        meta = table.current_snapshot()

        if meta is None:
            msg = f"No current snapshot for {table_name}".encode("utf-8")
        else:
            msg = f"Wrote {meta.added_rows} rows to {table_name}".encode("utf-8")
        writer.write(msg)

    def list_actions(
            self, context: flight.ServerCallContext
    ) -> Iterator[flight.ActionType]:
        """Flight has native support for actions.
        Actions are a way to perform arbitrary operations, and list_actions is a discovery
        mechanism for the client to find out what actions are available.
        """
        actions = [
            (
                "update_description",
                json.dumps(
                    {
                        "description": "Update a dataset description",
                        "schema": UpdateDatasetRequest.model_json_schema(),
                    }
                ),
            ),
            (
                "delete_dataset",
                json.dumps(
                    {
                        "description": "Delete a dataset",
                        "schema": DeleteDatasetRequest.model_json_schema(),
                    }
                ),
            ),
            (
                "get_active_user",
                json.dumps({
                    "description": "Get the active user",
                    "schema": None,
                })
            )
        ]

        for action in actions:
            yield flight.ActionType(action[0], action[1])

    def do_action(
            self, context: flight.ServerCallContext, action: flight.Action
    ) -> Iterator[bytes]:
        """When the client wants to perform an action, it will send an Action via do_action.
        What that action does is completely up to the implementation.
        """
        match action.type:
            case "update_description":
                request = UpdateDatasetRequest.model_validate_json(
                    action.body.to_pybytes().decode("utf-8")
                )
                try:
                    table = self._catalog.load_table(request.name)
                except NoSuchTableError:
                    raise flight.FlightServerError(f"Table {request.name} does not exist")
                with table.transaction() as tx:
                    tx.set_properties({"description": request.description})

                yield f"Updated dataset {request.name} description".encode("utf-8")
            case "delete_dataset":
                request = DeleteDatasetRequest.model_validate_json(
                    action.body.to_pybytes().decode("utf-8")
                )
                try:
                    self._catalog.drop_table(request.name)
                except NoSuchTableError:
                    raise flight.FlightServerError(f"Table {request.name} does not exist")

                yield f"Deleted dataset {request.name}".encode("utf-8")
            case "get_active_user":
                user = context.peer_identity()
                yield user
            case _:
                raise flight.FlightServerError(f"Unknown action: {action.type}")

    def do_exchange(
            self,
            _: flight.ServerCallContext,
            descriptor: flight.FlightDescriptor,
            reader: flight.FlightStreamReader,
            writer: flight.FlightStreamWriter,
    ):
        """Flight can receive and send data within the same call using do_exchange.
        This is commonly used for enriching data, such as calling an ML model to enrich the data,
        or calculate some metric on the data.
        """
        cmd: str = json.loads(descriptor.command.decode("utf-8"))["metric"]
        match cmd:
            case "ctr":
                sample_ctr_data: pa.Table = reader.read_all()
                df = pl.DataFrame(sample_ctr_data)
                min_date = cast(dt.date, df["date"].min())
                max_date = cast(dt.date, df["date"].max())

                sample_ctr = metrics.calculate_ctr(sample_ctr_data)

                table = self._catalog.load_table(f"{self.namespace}.metrics")

                total_data = table.scan(
                    row_filter=GreaterThanOrEqual(term="date", value=min_date) & LessThanOrEqual(term="date",
                                                                                                 value=max_date),
                    selected_fields=("date", "is_clicked"),
                ).to_arrow()

                total_ctr = metrics.calculate_ctr(total_data)
                result = total_ctr.append_column("sample_ctr", sample_ctr["click_rate"])
                writer.begin(result.schema)
                writer.write_table(result)
            case _:
                raise flight.FlightServerError(f"Unknown command: {cmd}")
