# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arrow-flight-server'
primary_region = 'arn'

[build]
image = "andersbogsnes/flight_server:1.0.1"

[http_service]
internal_port = 7000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.http_options]
h2_backend = true


[http_service.tls_options]
alpn = ["h2"]

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
